### ISSUE TITLE
must be a relative utf-8 path

### ISSUE THREAD

**Issue by patatetom** [jubako/arx#31]
hi,
I'm trying `arx` and get an error when I pass the input as an absolute path :
```console
$ cd /tmp/
$ mkdir test.arx.d/
$ cp ./arx test.arx.d/

$ # OK
$ ./arx -vvv create --outfile ./test.arx ./test.arx.d/
[INFO  arx::create] Creating archive Some("./test.arx")
[INFO  arx::create] With files ["./test.arx.d/"]
[DEBUG arx::create] Saved place is 0
$ rm -f test.arx

$ # KO
$ ./arx -vvv create --outfile ./test.arx /tmp/test.arx.d/
[INFO  arx::create] Creating archive Some("./test.arx")
[INFO  arx::create] With files ["/tmp/test.arx.d/"]
Well, this is embarrassing.
arx had a problem and crashed. To help us diagnose the problem you can send us a crash report.
We have generated a report file at "/tmp/report-a142a59f-fe43-41af-ad9e-c5fc2f1541c6.toml". Submit an issue or email with the subject of "arx Crash Report" and include the report as an attachment.
- Homepage: https://github.com/jubako/arx
- Authors: Matthieu Gautier <mgautier@kymeria.fr>
We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.
Thank you kindly!
$ cat /tmp/report-a142a59f-fe43-41af-ad9e-c5fc2f1541c6.toml
"name" = "arx"
"crate_version" = "0.2.1"
"explanation" = """
Panic occurred in file '/home/runner/work/arx/arx/libarx/src/create/fs_adder.rs' at line 146
"""
"cause" = "\"/tmp/test.arx.d/\" must be a relative utf-8 path."
"method" = "Panic"
"backtrace" = """
   0: 0x642f3c0fa4c5 - arx::create::create::h0d31a0a1c81133f8
   1: 0x642f3c09e6c0 - arx::main::h8e785563c91bb87e
   2: 0x642f3c10fd63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h512139b71798be16
   3: 0x642f3c0a99d2 - main
   4: 0x75fe15335c88 - <unresolved>
   5: 0x75fe15335d4c - __libc_start_main
   6: 0x642f3c092255 - _start
   7:        0x0 - <unresolved>"""
```
the problem remains if I install `arx` with `cargo`.
regards, lacsaP.

**Comment by cchristofr** [comment]
Same issue:


`arx create -o irstea_documents.arx -r Documents

Compressed Cluster   : ############################################+ 515  / 516 
Uncompressed Cluster : --------------------------------------------- 0    / 1   Well, this is embarrassing.

arx had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/tmp/report-ddf531c4-69ad-476d-9f5b-c602edea3b20.toml". Submit an issue or email with the subject of "arx Crash Report" and include the report as an attachment.

- Homepage: https://github.com/jubako/arx
- Authors: Matthieu Gautier <mgautier@kymeria.fr>

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
`
then:
`
christo:~$ cat /tmp/report-ddf531c4-69ad-476d-9f5b-c602edea3b20.toml
"name" = "arx"
"operating_system" = "Ubuntu 22.04 (jammy) [64-bit]"
"crate_version" = "0.2.1"
"explanation" = """
Panic occurred in file 'libarx/src/create/fs_adder.rs' at line 88
"""
"cause" = "\"/home/christo/Documents/PôleGD\" must be a relative utf-8 path"
"method" = "Panic"
"backtrace" = """

   0: 0x651652a4739c - libarx::create::entry_store_creator::DirEntry::add_entry::hfac430b68bc9369a
   1: 0x651652a479d8 - libarx::create::entry_store_creator::DirEntry::add::h6a26588866a85f93
   2: 0x651652a47c2d - libarx::create::entry_store_creator::DirEntry::add::h6a26588866a85f93
   3: 0x651652a5eee1 - arx::create::create::h0d31a0a1c81133f8
   4: 0x651652a036c0 - arx::main::h8e785563c91bb87e
   5: 0x651652a74d63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h512139b71798be16
   6: 0x651652a0e9d2 - main
   7: 0x7345bdc29d90 - __libc_start_call_main
                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   8: 0x7345bdc29e40 - __libc_start_main_impl
                at ./csu/../csu/libc-start.c:392
   9: 0x6516529f7255 - _start
  10:        0x0 - <unresolved>"""
christo:~$ 
`

**Comment by mgautierfr** [comment]
Thanks both of you for testing arx. I'm glade to see this project gain some attraction :)

I think this is two different issues. So @cchristofr I will move you comment in a new issue.

---

@patatetom I will fix the issue by better checking the input and print a better error message instead of crashing. Arx can only save relative path. We may infer a relative path from absolute but I think this is more tricky that we may think first.

**Comment by mgautierfr** [comment]
Arx archive cannot store absolute path. So the directory you want to add (`C:\Archive`) must be passed as relative path.

You can simply cd in C: first and use relative path:
```
$ cd C:\
$ arx.exe create -o out.arx -r Archive
```

**Comment by sergeevabc** [comment]
Oh… It's kinda weird, unexpected behaviour in the 21st century.

I'm used to the following

``` console
$ 7z.exe a out.tar C:\Private\Notes\Obsidian

7-Zip 24.09 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-11-29
Scanning the drive:
95 folders, 297 files, 9956018 bytes (9723 KiB)
Creating archive: out.tar
Add new data to archive: 95 folders, 297 files, 9956018 bytes (9723 KiB)
Files read from disk: 392
Archive size: 10257408 bytes (10017 KiB)
Everything is Ok

$ 7z.exe l out.tar
...
2024-01-09 04:53:24 .....         2218         2560  Obsidian\Languages\English.md
------------------- ----- ------------ ------------  ------------------------
2025-03-11 17:12:36            9956018     10034176  297 files, 95 folders
```

So you see, `7z` picks an absolute path without hesitation and then trims it automatically.

**Comment by mgautierfr** [comment]
I agree it could be better. But how to allow user to create an archive with all the directory tree (`Private`, `Private\Notes`, `Private\Notes\Obsidian`, `Private\Notes\Obsidian`) and not just have the last directory (`Obsidian`) ?

The current api is a bit odd but you can simply pass the path you want to have in the archive.

If you have propositions about how to design this (options, how to handle paths...) you are welcome (please open a new issue in this case)
